# flask + SQLite では docker-compose でコンテナを複数起動＆連携する
# 必要性が薄いが、拡張性を持たせるために docker-compose で書いておく

version: '3'
services: 
  flask:
    # カレントディレクトリの Dockerfile からイメージ構築
    build: .
    ports: 
      - "5000:5000"
    # ホスト上のカレントディレクトリをコンテナ内の /main ディレクトリにマウント
    volumes:
      - .:/main
    # RaspberryPi の GPIO や I2C を使用するためのオプション
#     devices:
#       - /dev/gpiomem
#       - /dev/i2c-1